In [47]:
type('this is a string')


str

In [48]:
type(1.0)

float

In [49]:
x=(1,'a',2,'b')
type(x)

tuple

In [6]:
y=[1,'a',2,'b']
y, type(y)

([1, 'a', 2, 'b'], list)

In [7]:
y.append(3.3)
y

[1, 'a', 2, 'b', 3.3]

In [8]:
for item in y:
    print(item)

1
a
2
b
3.3


In [10]:
x='this is a string'
print(x[0:1])
print(x[0:2])

t
th


In [11]:
x[3:]

's is a string'

In [1]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [2]:
type(lambda x: x+1) 

function

In [3]:
[x**2 for x in range(10)] 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [15]:
import numpy as np
r=np.ones((6,6))

In [16]:
r

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
r.reshape(36)[::7]

array([1., 1., 1., 1., 1., 1.])

In [19]:
r=(6,6)

In [20]:
r

(6, 6)

In [21]:
r = [x+1 for x in range(35)]

In [31]:
r=np.arange(36).reshape((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
r[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [33]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [34]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [35]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [36]:
r[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [38]:
r[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [39]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [40]:
r[2:3,2:3]

array([[14]])

In [46]:
r[1:2,1:2]

array([[7]])